### ISSUE TITLE
Handling spaces in paths

### ISSUE THREAD

**Issue by silvain** [ronen25/nautilus-copypath#11]
Thua extension is a saving-life thing for the present version of Nautilus.
One drawback for me is that it escapes spaces in filenames / pathnames when I paste them
Would it be a way to avoid this?

**Comment by ronen25** [comment]
Hi, thank you for the comment!

The space escaping is intentional - the original purpose of this extension was for me to copy file paths into a browser-like environment, which requires all spaces to be escaped. This is why currently, there is unfortunately no way to disable this behavior (other than modifying it in the code of course).

I'm thinking that this could be implemented fairly easily though. Say if some modifier key (like Shift) is being pressed, then we copy the spaces as-is instead of escaping them. Haven't used Nautilus in a while, but I think this should be OK with the Gnome guidelines.
Will this solution be OK?

Thanks.
